# Configuration for Example Jobs Site (for testing)
site_name: "Example Jobs"
start_url: "https://example.com/jobs"

# Selectors to find the data on the page
selectors:
  job_container: ".job-listing, .job-item, .position"
  title: ".job-title, .position-title, h3::text"
  company: ".company-name, .employer::text"
  location: ".location, .city::text"
  date_posted: ".date-posted, .posted-date::text"
  apply_url: "a[href*='apply'], .apply-link::attr(href)"
  description: ".job-description, .summary::text"
  salary: ".salary, .compensation::text"

# How to handle moving to the next page
pagination:
  next_page_selector: "a[rel='next'], .next-page::attr(href)"

# Additional configuration
scraping_options:
  use_scraperapi: false
  delay_between_requests: 2
  max_pages: 3
