# Configuration for Indeed Jobs Portal
site_name: "Indeed"
start_url: "https://www.indeed.com/jobs?q=software+engineer&l="

# Selectors to find the data on the page
selectors:
  job_container: "[data-jk], .jobsearch-SerpJobCard, .result"
  title: ".jobTitle a span::text, .jobTitle::text"
  company: ".companyName a::text, .companyName::text"
  location: ".companyLocation::text, .location::text"
  date_posted: ".date::text, .datePosted::text"
  apply_url: ".jobTitle a::attr(href)"
  description: ".summary::text, .job-snippet::text"
  salary: ".salaryText::text, .salary-snippet::text"

# How to handle moving to the next page
pagination:
  next_page_selector: "a[aria-label='Next Page']::attr(href)"

# Additional configuration
scraping_options:
  use_scraperapi: false
  delay_between_requests: 3
  max_pages: 5
