# Configuration for LinkedIn Jobs Portal
site_name: "LinkedIn"
start_url: "https://www.linkedin.com/jobs/search/?keywords=software%20engineer"

# Selectors to find the data on the page
selectors:
  job_container: ".jobs-search-results__list-item, .job-card-container"
  title: ".job-card-list__title a::text, .job-card-list__title::text"
  company: ".job-card-container__company-name::text, .job-card-container__metadata-item a::text"
  location: ".job-card-container__metadata-item::text"
  date_posted: ".job-card-container__metadata-item time::attr(datetime)"
  apply_url: ".job-card-list__title a::attr(href)"
  description: ".job-card-container__description::text"

# How to handle moving to the next page
pagination:
  next_page_selector: "button[aria-label='Next']::attr(data-offset)"

# Additional configuration
scraping_options:
  use_scraperapi: true
  delay_between_requests: 4
  max_pages: 3
